name: CI-HelloWorld

on:
  push:
    branches:
      - enh/actionsimplementation
  workflow_dispatch:

jobs:
  with-checkout-job:
    name: With Checkout
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run before build
        run: |
          sudo apt-get install -y tree
          tree .

      - name: Install python and Build
        run: |
          sudo apt-get install -y python3 python3-pip
          sudo pip install --upgrade build

      - name: Build
        run: |
          sudo python -m build
        
      - name: Tree after build
        run: |
          tree .

        
